### PR TITLE
Port to Node JS

### LINKED ISSUE #28: convert entrypoint to js
The entrypoint file is in bash, which is an unwieldy, barely readable language. Despite the efforts to make bash more friendly, JavaScript would make for a much more flexible/maintainable language.

That said, when using the node ecosystem, updates/maintenance essentially becomes required so I'm very open to changing to a slower moving language.

### PR DESCRIPTION
**Pull request by RGonzalezTech**
## Summary

Updated the `Dockerfile` to use a node image and wrote the behavior using Node.JS + `jest` for TDD. I also added a github action that will run the jest tests on PRs and pushes to `master`. (`.github/workflows/node-tests.yml`).

`index.js` is the entrypoint. We use:

- The `yargs` package to parse CLI input flags. 
- The `fast-xml-parser` package to parse the result XML
- The `decompress` package to unzip the download.

The tests cover a edge-cases and most branching logic.

 **_I'll resolve the .net install on docker Soon™_**
I was developing on a branch that didn't include the Dockerfile changes from 4e8e966 and only recently rebased it😅

## Quick Code Notes

It's basically the exact same behavior as before, but I am making more use of functions and unit tests to make sure behavior is covered. 

- `getCliArgs()` - returns parsed arguments from the command line using the `yargs` library.
- `downloadGodot()` returns the path to the executable
- `analyzeTestResults()` uses the `fast-xml-parser` package to parse the result XML. This package only has 1 dependency.
- We make use of environmental variables & CLI args, and we mock these values in our unit tests to make sure the functions behave as expected
- I've included [the example test](https://bitwes.github.io/GutWiki/Godot4/Export-Test-Results.html) from the GUT documents under `test_fixtures/testResults.xml` to make sure our code is robust enough to handle it.

## Related Issue
Closes #28

### CODE REVIEW

**Comment by croconut** [comment]
Whoops, never made this clear but since we're doing node, we should look into going containerless. I've tested out that our code would work, most of my question was whether we'd be able to write files on the test runner, and it seemed to go well

**Comment by croconut** [comment]
@RGonzalezTech I had a branch I started that had that config if you'd like to add to this one. Also I see you're commiting project lock, if were doing that we'd want to use npm ci and start a dependabot service.

**Comment by RGonzalezTech** [comment]
## Dockerfile

> @RGonzalezTech I had a branch I started that had that config if you'd like to add to this one. Also I see you're commiting project lock, if were doing that we'd want to use npm ci and start a dependabot service.

I'll update the dockerfile to use `npm ci` instead and I'll check out the docker steps in your branch.

## Containerless

> Whoops, never made this clear but since we're doing node, we should look into going containerless. I've tested out that our code would work, most of my question was whether we'd be able to write files on the test runner, and it seemed to go well

How would you feel about switching to containerless in another PR/version? This seems to work fine and it has the benefit of managing all of the dependencies separate from any project we'd be interacting with.

## Dependabot

I've never set up Dependabot before, but I can take a look at that, too. Do you have any helpful resources for me or could you branch off of this PR branch to add it?

I've got some work to do today, but I'll check this stuff out Soon™ haha
Thanks :)

**Comment by RGonzalezTech** [comment]
Updated the Dockerfile to use the ubuntu image and install node via `RUN` commands.

RE Dependabot - I don't have access to the settings for this repository, so I don't know if I can turn it on or off. I see that it's enabled for alerts in the Security tab, though.

image

Let me know if this is good to merge & release 👍

**Comment by croconut** [comment]
Okay looks good to me. I'll add an issue to specifically do the swap to containerless. 

I'll also add an issue to add the .gitattributes so we're ignoring the test directories for releases, and in the containerless PR, I'll have a step for release / tests to include the package bundling process

**Review by croconut — APPROVED** [review]
That's uhh a lot of files. Doesnt seem necessary to me, but the works already been done. LGTM

**Pull request merged**
